In [42]:
# Variables que tenemos:
# - % de rotaciones por gerente (pq tenemos mas de un %rotación por gerente?)
# - (vamos a tener) respuestas
# - edad y vigencia por gerente (donde?)
# - variables de contexto:
# - - variables económicas del estado
# - - salario promedio del estado (para la posición?)
# - - demográficas por estado (tasa de desocupación por estado)
# Variables que queremos:
# - fecha de la toma de la rotación
# - salario de los empleados del gerente (puede ser solo promedio)
# - variables de contexto:
# - - del centro (cuanta gente hay, departamentos, etc)
# Por hacer:
# - promedio de %Rotación por centro o estado (para contrastar el %Rotación por gerente)
# - realizar análisis de sentimientos sobre respuestas
# - obtener correlaciones / grafos
# - clustering

# NOTAS:
# En regiones no hallamos CDMX, sino DF. Mientras que en cursos se usa CDMX
# ==================================================
# Del cliente:
# datos, variable objetivo
# objetivo general
# especificaciones activos a entregar
# dashboard
# aplicación web
# api
# documentos
# De nosotros
# documento eda
# documento de análisis
# requerimentos-solicitados.

In [43]:
import pandas as pd
from datetime import datetime, date, time, timedelta

In [44]:
uv add pandas numpy matplotlib seaborn

Note: you may need to restart the kernel to use updated packages.

c:\Users\jose.rodriguezb\Desktop\rotacion_encuestas\.venv\Scripts\python.exe: No module named uv

# Importar datos

## Topics de Respuestas de Encuestas

In [45]:
lda_topics_df = pd.read_csv("../data/LDA_res.csv")

In [46]:
lda_topics_df.drop(columns=["Unnamed: 0"], inplace=True)

In [47]:
lda_topics_df

,P1_n_0,P1_n_1,P1_n_2,P1_n_3,P1_n_4,P1_n_5,P1_n_6,P1_n_7,P1_n_8,P1_n_9,...,P6_v_0,P6_v_1,P6_v_2,P6_v_3,P6_v_4,P6_v_5,P6_v_6,P6_v_7,P6_v_8,P6_v_9
0,0.045477,0.040022,0.607325,0.037355,0.035648,0.053731,0.038457,0.048750,0.043515,0.049721,...,0.014515,0.507785,0.016995,0.193793,0.015922,0.017781,0.017257,0.017365,0.184314,0.014272
1,0.151717,0.150014,0.052267,0.011673,0.011139,0.016790,0.012017,0.015233,0.426117,0.153033,...,0.388122,0.011090,0.011306,0.387948,0.010595,0.011830,0.011481,0.011553,0.011129,0.144946
2,0.019601,0.017250,0.261728,0.016100,0.015364,0.212832,0.016575,0.400365,0.018755,0.021430,...,0.000000,0.000000,0.523050,0.000000,0.000000,0.228939,0.000000,0.000000,0.213236,0.000000
3,0.024189,0.021287,0.320690,0.019869,0.254365,0.028579,0.020455,0.025942,0.258178,0.026446,...,0.089603,0.102865,0.104874,0.089640,0.098283,0.109725,0.106507,0.107172,0.103234,0.088098
4,0.031580,0.027792,0.116152,0.025943,0.024755,0.037311,0.026705,0.645017,0.030217,0.034527,...,0.014516,0.016667,0.854986,0.014521,0.015921,0.017778,0.017253,0.017362,0.016723,0.014272
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5028,0.045477,0.040022,0.607325,0.037355,0.035648,0.053731,0.038457,0.048750,0.043515,0.049721,...,0.089603,0.102865,0.104874,0.089640,0.098283,0.109725,0.106507,0.107172,0.103234,0.088098
5029,0.014210,0.150013,0.189753,0.011673,0.011140,0.016789,0.012017,0.290262,0.013597,0.290546,...,0.012432,0.014274,0.710062,0.012437,0.013637,0.015227,0.014781,0.180604,0.014323,0.012224
5030,0.016480,0.185043,0.060599,0.013533,0.012915,0.178880,0.013933,0.017663,0.482936,0.018018,...,0.000000,0.268405,0.506337,0.000000,0.194717,0.000000,0.000000,0.000000,0.000000,0.000000
5031,0.045477,0.040022,0.167266,0.477352,0.035648,0.053763,0.038457,0.048750,0.043515,0.049750,...,0.089603,0.102865,0.104874,0.089640,0.098283,0.109725,0.106507,0.107172,0.103234,0.088098
5032,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,0.136389,0.012482,0.012728,0.010876,0.491484,0.013319,0.286498,0.013006,0.012530,0.010689

In [48]:
## Edad y vigencia por gerente

In [49]:
from datetime import datetime
import numpy as np
import pandas as pd
import os

# Opción 1: Ruta relativa (si el archivo está en la misma carpeta)
file_path = '../data/Sondeo  -   Perspectiva del Gerente sobre Rotación  (Respuestas).xlsx'



# Verificar si el archivo existe
if os.path.exists(file_path):
    datosEncuestas = pd.read_excel(file_path, sheet_name='Respuestas de formulario 1')
else:
    print(f"El archivo no se encuentra en: {file_path}")

In [50]:
datosEncuestas = pd.DataFrame(datosEncuestas).astype('str')

In [51]:
datosEncuestas.columns = datosEncuestas.iloc[0,:]
datosEncuestas.drop([0],inplace=True)
datosEncuestas.reset_index(drop=True, inplace=True)

In [52]:
numEmpleado = datosEncuestas[datosEncuestas.columns[1]].to_frame()
numEmpleado.columns = ["numEmpleado"]
numEmpleado["numEmpleado"] = numEmpleado["numEmpleado"].apply(int)

In [53]:
numEmpleado

      numEmpleado
0        92650554
1        92109391
2        90391277
3        90269515
4        94566526
...           ...
4991     90372744
4992     95258426
4993     97238287
4994     96848332
4995     93557515

[4996 rows x 1 columns]

## datos de empleados..

In [54]:
# datosEncuestas = gc.open(r"GCP_Core_Plantilla_ActivaVSAutorizada_REP_8")
# # datosEncuestas = datosEncuestas.worksheet("Tabla dinámica 1").get_all_values() #value_render_option=ValueRenderOption.unformatted)
# # datosEncuestas = pd.DataFrame(datosEncuestas).astype('str')
full_gcp_core_sheet = pd.read_csv("../data/GCP_Core_Plantilla_ActivaVSAutorizada_REP_8_Sheet1.csv")
full_gcp_core_sheet

C:\Users\jose.rodriguezb\AppData\Local\Temp\ipykernel_14728\1724008386.py:4: DtypeWarning: Columns (1,11,19,31,32,33,34,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  full_gcp_core_sheet = pd.read_csv("../data/GCP_Core_Plantilla_ActivaVSAutorizada_REP_8_Sheet1.csv")

,Fecha de inicio de vigencia,Fecha de cierre,Estado,Estado Contratación,Posición presupuestada,Importe,Centro de costos,Centro,Ubicación,Región,...,Tipo de Trabajador,Codigo de posición principal,Nombre de posición principal,Número de persona del manager,Número de trabajador del manager,Nombre del manager,Número de Persona,Nombre Completo,Unnamed: 43,Unnamed: 44
0,08/09/2025,01/10/2025,Activa,Aprobada,Sí,$1.00,004 - BANCO,3480,MX-01-SON-33 - T15-OBREGON IV-33,HERMOSILLO,...,NaN,39725.0,GERENTE DE SERVICIOS FINANCIEROS,98128922.0,98128922.0,Ana Lucia Ruiz Ozuna,90102819.0,Lizeth Guadalupe Otañez Angulo,HERMOSILLO,PROMOTOR DE BANCO
1,08/09/2025,07/11/2025,Activa,Congelada,Sí,$1.00,002 - TDAS ROPA,779802,MX-01-SIN-1604 - T02-EXPLANADA CULIACAN-1604,CULIACAN,...,NaN,140277.0,GERENTE DE TIENDA ROPA,96994436.0,96994436.0,Maria Luisa Rojas Garcia,90300093.0,Brayan Ulises Chaidez Meza,CULIACAN,ASESOR DE VENTAS
2,08/09/2025,14/08/2025,Inactiva,Congelada,No,$0.00,003 - TDAS CAJAS,87203,MX-01-MEX-795 - T19-PLAZA SANTINI-795,TOLUCA,...,NaN,73554.0,GERENTE DE SERVICIOS FINANCIEROS,NaN,NaN,NaN,90317693.0,Ana Rebeca Moreno Valenzuela,TOLUCA,CAJERO DE ABONOS
3,08/09/2025,15/01/2026,Activa,Congelada,Sí,$1.00,072 - TRASLADO,200133,MX-02-SIN-137 - T02-CULIACAN-137,CULIACAN,...,Colaborador,31799.0,GERENTE DE TRASLADO,91564395.0,91564395.0,Eugenio Franco Eseberre,NaN,NaN,CULIACAN,SURTIDOR
4,08/09/2025,15/01/2026,Activa,Congelada,Sí,$1.00,072 - TRASLADO,200133,MX-02-SIN-137 - T02-CULIACAN-137,CULIACAN,...,Colaborador,31799.0,GERENTE DE TRASLADO,91564395.0,91564395.0,Eugenio Franco Eseberre,NaN,NaN,CULIACAN,SURTIDOR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199594,25/04/2025,NaN,Inactiva,Aprobada,Sí,$1.00,150 - INVENTARIOS TIENDA,300632,MX-03-OAX-135 - C13-MIAHUATLAN DE PORFIRIO DIA...,OAXACA,...,NaN,97469,GERENTE DE ZONA TIENDA,95742948.0,95742948.0,Martha Ramirez Jimenez,NaN,NaN,OAXACA,AUXILIAR DE INVENTARIOS
199595,25/04/2025,NaN,Inactiva,Aprobada,Sí,$1.00,150 - INVENTARIOS TIENDA,356957,MX-04-MEX-81 - R05-NCPN ZONA-81,AZCAPOTZALCO,...,NaN,95452,ENTRENAMIENTO ZONA,100093675.0,90461795.0,Reyna Karina Sanchez Rodriguez,NaN,NaN,AZCAPOTZALCO,AUXILIAR DE INVENTARIOS
199596,25/04/2025,NaN,Inactiva,Aprobada,Sí,$1.00,150 - INVENTARIOS TIENDA,300206,MX-05-NL-38 - R07-OFICINA MONTERREY BANCOPPEL-...,MONTERREY,...,NaN,95840,GERENTE DE ZONA TIENDA,93783205.0,93783205.0,Cesar Jesus Francisc Reyna Salazar,NaN,NaN,MONTERREY,AUXILIAR DE INVENTARIOS
199597,25/04/2025,NaN,Inactiva,Aprobada,Sí,$1.00,150 - INVENTARIOS TIENDA,329112,MX-05-SIN-20 - R01-CORPORATIVO AMPLIACION-COPP...,CULIACAN,...,NaN,95883,GERENTE DE ZONA TIENDA,90042565.0,90042565.0,Cesar Humberto Favela Valenzuela,NaN,NaN,CULIACAN,AUXILIAR DE INVENTARIOS
199598,25/04/2025,NaN,Inactiva,Aprobada,Sí,$1.00,305 - ACTIVADO DE MOTOS,211502,MX-04-MEX-74 - R20-TOLC PERSONAL-74,TOLUCA,...,NaN,132825,JEFE DE ACTIVACION DE MOTOS,90041601.0,90041601.0,Paulina Arriaga Cruz,NaN,NaN,TOLUCA,MECANICO DE MOTOS

In [55]:
full_gcp_core_sheet.columns

Index(['Fecha de inicio de vigencia', 'Fecha de cierre', 'Estado',
       'Estado Contratación', 'Posición presupuestada', 'Importe',
       'Centro de costos', 'Centro', 'Ubicación', 'Región', 'Ciudad',
       'Empleador legal', 'Unidad de negocio', 'División', 'Departamento',
       'Código de puesto', 'Nombre de puesto', 'Familia de puesto',
       'Función del puesto', 'Código de posición', 'Nombre de posición',
       'Indefinido o temporal', 'Tipo de presupuesto ',
       'Categoria de asignación', 'Plantilla Autorizada', 'Plantilla Activa',
       'Vacantes', 'Grupo salarial', 'Rol de contribución',
       'Número de persona', 'Número de trabajador', 'Nombre del colaborador',
       'Fecha de antigüedad Grupo',
       'Fecha de contratación empleador legal actual',
       'Fecha de entrada en posición actual', 'Tipo de Trabajador',
       'Codigo de posición principal', 'Nombre de posición principal',
       'Número de persona del manager', 'Número de trabajador del manager',
       'Nombre del manager', 'Número de Persona', 'Nombre Completo',
       'Unnamed: 43', 'Unnamed: 44'],
      dtype='object')

In [56]:
full_gcp_core_sheet.rename(columns={"Número de trabajador": "numEmpleado"}, inplace=True)
# full_gcp_core_sheet.dropna(subset=["numEmpleado"], inplace=True)
full_gcp_core_sheet["numEmpleado"] = full_gcp_core_sheet["numEmpleado"].astype("Int64")
full_gcp_core_sheet["Fecha de inicio de vigencia"] = full_gcp_core_sheet["Fecha de inicio de vigencia"].apply(lambda x: datetime.strptime(x, "%d/%m/%Y"))
full_gcp_core_sheet

,Fecha de inicio de vigencia,Fecha de cierre,Estado,Estado Contratación,Posición presupuestada,Importe,Centro de costos,Centro,Ubicación,Región,...,Tipo de Trabajador,Codigo de posición principal,Nombre de posición principal,Número de persona del manager,Número de trabajador del manager,Nombre del manager,Número de Persona,Nombre Completo,Unnamed: 43,Unnamed: 44
0,2025-09-08,01/10/2025,Activa,Aprobada,Sí,$1.00,004 - BANCO,3480,MX-01-SON-33 - T15-OBREGON IV-33,HERMOSILLO,...,NaN,39725.0,GERENTE DE SERVICIOS FINANCIEROS,98128922.0,98128922.0,Ana Lucia Ruiz Ozuna,90102819.0,Lizeth Guadalupe Otañez Angulo,HERMOSILLO,PROMOTOR DE BANCO
1,2025-09-08,07/11/2025,Activa,Congelada,Sí,$1.00,002 - TDAS ROPA,779802,MX-01-SIN-1604 - T02-EXPLANADA CULIACAN-1604,CULIACAN,...,NaN,140277.0,GERENTE DE TIENDA ROPA,96994436.0,96994436.0,Maria Luisa Rojas Garcia,90300093.0,Brayan Ulises Chaidez Meza,CULIACAN,ASESOR DE VENTAS
2,2025-09-08,14/08/2025,Inactiva,Congelada,No,$0.00,003 - TDAS CAJAS,87203,MX-01-MEX-795 - T19-PLAZA SANTINI-795,TOLUCA,...,NaN,73554.0,GERENTE DE SERVICIOS FINANCIEROS,NaN,NaN,NaN,90317693.0,Ana Rebeca Moreno Valenzuela,TOLUCA,CAJERO DE ABONOS
3,2025-09-08,15/01/2026,Activa,Congelada,Sí,$1.00,072 - TRASLADO,200133,MX-02-SIN-137 - T02-CULIACAN-137,CULIACAN,...,Colaborador,31799.0,GERENTE DE TRASLADO,91564395.0,91564395.0,Eugenio Franco Eseberre,NaN,NaN,CULIACAN,SURTIDOR
4,2025-09-08,15/01/2026,Activa,Congelada,Sí,$1.00,072 - TRASLADO,200133,MX-02-SIN-137 - T02-CULIACAN-137,CULIACAN,...,Colaborador,31799.0,GERENTE DE TRASLADO,91564395.0,91564395.0,Eugenio Franco Eseberre,NaN,NaN,CULIACAN,SURTIDOR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199594,2025-04-25,NaN,Inactiva,Aprobada,Sí,$1.00,150 - INVENTARIOS TIENDA,300632,MX-03-OAX-135 - C13-MIAHUATLAN DE PORFIRIO DIA...,OAXACA,...,NaN,97469,GERENTE DE ZONA TIENDA,95742948.0,95742948.0,Martha Ramirez Jimenez,NaN,NaN,OAXACA,AUXILIAR DE INVENTARIOS
199595,2025-04-25,NaN,Inactiva,Aprobada,Sí,$1.00,150 - INVENTARIOS TIENDA,356957,MX-04-MEX-81 - R05-NCPN ZONA-81,AZCAPOTZALCO,...,NaN,95452,ENTRENAMIENTO ZONA,100093675.0,90461795.0,Reyna Karina Sanchez Rodriguez,NaN,NaN,AZCAPOTZALCO,AUXILIAR DE INVENTARIOS
199596,2025-04-25,NaN,Inactiva,Aprobada,Sí,$1.00,150 - INVENTARIOS TIENDA,300206,MX-05-NL-38 - R07-OFICINA MONTERREY BANCOPPEL-...,MONTERREY,...,NaN,95840,GERENTE DE ZONA TIENDA,93783205.0,93783205.0,Cesar Jesus Francisc Reyna Salazar,NaN,NaN,MONTERREY,AUXILIAR DE INVENTARIOS
199597,2025-04-25,NaN,Inactiva,Aprobada,Sí,$1.00,150 - INVENTARIOS TIENDA,329112,MX-05-SIN-20 - R01-CORPORATIVO AMPLIACION-COPP...,CULIACAN,...,NaN,95883,GERENTE DE ZONA TIENDA,90042565.0,90042565.0,Cesar Humberto Favela Valenzuela,NaN,NaN,CULIACAN,AUXILIAR DE INVENTARIOS
199598,2025-04-25,NaN,Inactiva,Aprobada,Sí,$1.00,305 - ACTIVADO DE MOTOS,211502,MX-04-MEX-74 - R20-TOLC PERSONAL-74,TOLUCA,...,NaN,132825,JEFE DE ACTIVACION DE MOTOS,90041601.0,90041601.0,Paulina Arriaga Cruz,NaN,NaN,TOLUCA,MECANICO DE MOTOS

## merged

In [57]:
lda_topics_df = pd.concat([lda_topics_df, numEmpleado], axis=1)
gcp_core_sheet = lda_topics_df.merge(full_gcp_core_sheet, on="numEmpleado", how="left")

In [58]:
gcp_core_sheet

,P1_n_0,P1_n_1,P1_n_2,P1_n_3,P1_n_4,P1_n_5,P1_n_6,P1_n_7,P1_n_8,P1_n_9,...,Tipo de Trabajador,Codigo de posición principal,Nombre de posición principal,Número de persona del manager,Número de trabajador del manager,Nombre del manager,Número de Persona,Nombre Completo,Unnamed: 43,Unnamed: 44
0,0.045477,0.040022,0.607325,0.037355,0.035648,0.053731,0.038457,0.048750,0.043515,0.049721,...,Colaborador,96406,GERENTE DE ZONA TIENDA,92121438.0,92121438.0,Sebastian Cruz Alvarado,NaN,NaN,TECAMAC,GERENTE DE TIENDA MUEBLES
1,0.151717,0.150014,0.052267,0.011673,0.011139,0.016790,0.012017,0.015233,0.426117,0.153033,...,Colaborador,2521,GERENTE DE ZONA DE COBRANZA,95578927.0,95578927.0,Martin Ernesto Corona Garcia,NaN,NaN,MEXICALI,GERENTE DE OPERACION COBRANZA
2,0.019601,0.017250,0.261728,0.016100,0.015364,0.212832,0.016575,0.400365,0.018755,0.021430,...,Colaborador,2589,GERENTE DE ZONA DE COBRANZA,90373031.0,90373031.0,Joel Cesar Medina Helguera,NaN,NaN,CD JUAREZ,GERENTE DE OPERACION COBRANZA
3,0.024189,0.021287,0.320690,0.019869,0.254365,0.028579,0.020455,0.025942,0.258178,0.026446,...,Colaborador,94558,GERENTE DE ZONA TIENDA,94012131.0,94012131.0,Javier Vargas Bedolla,NaN,NaN,TOLUCA,GERENTE DE TIENDA ROPA
4,0.031580,0.027792,0.116152,0.025943,0.024755,0.037311,0.026705,0.645017,0.030217,0.034527,...,Colaborador,97399,GERENTE DE ZONA TIENDA,91490782.0,91490782.0,Edgar Isaac Mogica Betancourt,NaN,NaN,TEXCOCO,GERENTE DE TIENDA MOTOS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2844815,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,NaN,97469,GERENTE DE ZONA TIENDA,95742948.0,95742948.0,Martha Ramirez Jimenez,NaN,NaN,OAXACA,AUXILIAR DE INVENTARIOS
2844816,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,NaN,95452,ENTRENAMIENTO ZONA,100093675.0,90461795.0,Reyna Karina Sanchez Rodriguez,NaN,NaN,AZCAPOTZALCO,AUXILIAR DE INVENTARIOS
2844817,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,NaN,95840,GERENTE DE ZONA TIENDA,93783205.0,93783205.0,Cesar Jesus Francisc Reyna Salazar,NaN,NaN,MONTERREY,AUXILIAR DE INVENTARIOS
2844818,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,NaN,95883,GERENTE DE ZONA TIENDA,90042565.0,90042565.0,Cesar Humberto Favela Valenzuela,NaN,NaN,CULIACAN,AUXILIAR DE INVENTARIOS
2844819,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,NaN,132825,JEFE DE ACTIVACION DE MOTOS,90041601.0,90041601.0,Paulina Arriaga Cruz,NaN,NaN,TOLUCA,MECANICO DE MOTOS

In [59]:
gcp_core_sheet[gcp_core_sheet["Estado"].isna()]  # que significa o representa esto? (100 datos faltantes...)

,P1_n_0,P1_n_1,P1_n_2,P1_n_3,P1_n_4,P1_n_5,P1_n_6,P1_n_7,P1_n_8,P1_n_9,...,Tipo de Trabajador,Codigo de posición principal,Nombre de posición principal,Número de persona del manager,Número de trabajador del manager,Nombre del manager,Número de Persona,Nombre Completo,Unnamed: 43,Unnamed: 44
9,0.019601,0.017250,0.072092,0.394463,0.015365,0.023158,0.396871,0.021016,0.018755,0.021430,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,0.024188,0.021287,0.294843,0.516163,0.018961,0.028578,0.020455,0.025934,0.023145,0.026446,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,0.045477,0.040022,0.607325,0.037355,0.035648,0.053731,0.038457,0.048750,0.043515,0.049721,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,0.024188,0.021287,0.319607,0.019869,0.490480,0.028578,0.020455,0.025929,0.023161,0.026446,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,0.031580,0.027792,0.116152,0.637101,0.024755,0.037311,0.026705,0.033859,0.030217,0.034527,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4855,0.031580,0.027792,0.116153,0.025940,0.024755,0.342895,0.026705,0.033853,0.335772,0.034555,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4896,0.031589,0.027792,0.116153,0.025940,0.024755,0.037312,0.334918,0.033853,0.030218,0.337471,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4904,0.024190,0.443771,0.091693,0.019869,0.295922,0.028579,0.020455,0.025932,0.023146,0.026446,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4984,0.045477,0.040022,0.607325,0.037355,0.035648,0.053731,0.038457,0.048750,0.043515,0.049721,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4991,0.014211,0.221733,0.365686,0.011672,0.011140,0.016789,0.012017,0.317614,0.013598,0.015540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
gcp_core_sheet.dropna(subset=["Estado"], inplace=True)

In [61]:
gcp_core_sheet

,P1_n_0,P1_n_1,P1_n_2,P1_n_3,P1_n_4,P1_n_5,P1_n_6,P1_n_7,P1_n_8,P1_n_9,...,Tipo de Trabajador,Codigo de posición principal,Nombre de posición principal,Número de persona del manager,Número de trabajador del manager,Nombre del manager,Número de Persona,Nombre Completo,Unnamed: 43,Unnamed: 44
0,0.045477,0.040022,0.607325,0.037355,0.035648,0.053731,0.038457,0.048750,0.043515,0.049721,...,Colaborador,96406,GERENTE DE ZONA TIENDA,92121438.0,92121438.0,Sebastian Cruz Alvarado,NaN,NaN,TECAMAC,GERENTE DE TIENDA MUEBLES
1,0.151717,0.150014,0.052267,0.011673,0.011139,0.016790,0.012017,0.015233,0.426117,0.153033,...,Colaborador,2521,GERENTE DE ZONA DE COBRANZA,95578927.0,95578927.0,Martin Ernesto Corona Garcia,NaN,NaN,MEXICALI,GERENTE DE OPERACION COBRANZA
2,0.019601,0.017250,0.261728,0.016100,0.015364,0.212832,0.016575,0.400365,0.018755,0.021430,...,Colaborador,2589,GERENTE DE ZONA DE COBRANZA,90373031.0,90373031.0,Joel Cesar Medina Helguera,NaN,NaN,CD JUAREZ,GERENTE DE OPERACION COBRANZA
3,0.024189,0.021287,0.320690,0.019869,0.254365,0.028579,0.020455,0.025942,0.258178,0.026446,...,Colaborador,94558,GERENTE DE ZONA TIENDA,94012131.0,94012131.0,Javier Vargas Bedolla,NaN,NaN,TOLUCA,GERENTE DE TIENDA ROPA
4,0.031580,0.027792,0.116152,0.025943,0.024755,0.037311,0.026705,0.645017,0.030217,0.034527,...,Colaborador,97399,GERENTE DE ZONA TIENDA,91490782.0,91490782.0,Edgar Isaac Mogica Betancourt,NaN,NaN,TEXCOCO,GERENTE DE TIENDA MOTOS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2844815,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,NaN,97469,GERENTE DE ZONA TIENDA,95742948.0,95742948.0,Martha Ramirez Jimenez,NaN,NaN,OAXACA,AUXILIAR DE INVENTARIOS
2844816,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,NaN,95452,ENTRENAMIENTO ZONA,100093675.0,90461795.0,Reyna Karina Sanchez Rodriguez,NaN,NaN,AZCAPOTZALCO,AUXILIAR DE INVENTARIOS
2844817,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,NaN,95840,GERENTE DE ZONA TIENDA,93783205.0,93783205.0,Cesar Jesus Francisc Reyna Salazar,NaN,NaN,MONTERREY,AUXILIAR DE INVENTARIOS
2844818,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,NaN,95883,GERENTE DE ZONA TIENDA,90042565.0,90042565.0,Cesar Humberto Favela Valenzuela,NaN,NaN,CULIACAN,AUXILIAR DE INVENTARIOS
2844819,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,NaN,132825,JEFE DE ACTIVACION DE MOTOS,90041601.0,90041601.0,Paulina Arriaga Cruz,NaN,NaN,TOLUCA,MECANICO DE MOTOS

In [62]:
dropped_cols = []
for col in gcp_core_sheet.columns:
  lenn = len(gcp_core_sheet[col].unique())
  if lenn == 1:
    dropped_cols.append(col)
gcp_core_sheet.drop(dropped_cols, axis=1, inplace=True)
print("dropped these cols:", dropped_cols)

dropped these cols: []

In [63]:
gcp_core_sheet

,P1_n_0,P1_n_1,P1_n_2,P1_n_3,P1_n_4,P1_n_5,P1_n_6,P1_n_7,P1_n_8,P1_n_9,...,Tipo de Trabajador,Codigo de posición principal,Nombre de posición principal,Número de persona del manager,Número de trabajador del manager,Nombre del manager,Número de Persona,Nombre Completo,Unnamed: 43,Unnamed: 44
0,0.045477,0.040022,0.607325,0.037355,0.035648,0.053731,0.038457,0.048750,0.043515,0.049721,...,Colaborador,96406,GERENTE DE ZONA TIENDA,92121438.0,92121438.0,Sebastian Cruz Alvarado,NaN,NaN,TECAMAC,GERENTE DE TIENDA MUEBLES
1,0.151717,0.150014,0.052267,0.011673,0.011139,0.016790,0.012017,0.015233,0.426117,0.153033,...,Colaborador,2521,GERENTE DE ZONA DE COBRANZA,95578927.0,95578927.0,Martin Ernesto Corona Garcia,NaN,NaN,MEXICALI,GERENTE DE OPERACION COBRANZA
2,0.019601,0.017250,0.261728,0.016100,0.015364,0.212832,0.016575,0.400365,0.018755,0.021430,...,Colaborador,2589,GERENTE DE ZONA DE COBRANZA,90373031.0,90373031.0,Joel Cesar Medina Helguera,NaN,NaN,CD JUAREZ,GERENTE DE OPERACION COBRANZA
3,0.024189,0.021287,0.320690,0.019869,0.254365,0.028579,0.020455,0.025942,0.258178,0.026446,...,Colaborador,94558,GERENTE DE ZONA TIENDA,94012131.0,94012131.0,Javier Vargas Bedolla,NaN,NaN,TOLUCA,GERENTE DE TIENDA ROPA
4,0.031580,0.027792,0.116152,0.025943,0.024755,0.037311,0.026705,0.645017,0.030217,0.034527,...,Colaborador,97399,GERENTE DE ZONA TIENDA,91490782.0,91490782.0,Edgar Isaac Mogica Betancourt,NaN,NaN,TEXCOCO,GERENTE DE TIENDA MOTOS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2844815,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,NaN,97469,GERENTE DE ZONA TIENDA,95742948.0,95742948.0,Martha Ramirez Jimenez,NaN,NaN,OAXACA,AUXILIAR DE INVENTARIOS
2844816,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,NaN,95452,ENTRENAMIENTO ZONA,100093675.0,90461795.0,Reyna Karina Sanchez Rodriguez,NaN,NaN,AZCAPOTZALCO,AUXILIAR DE INVENTARIOS
2844817,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,NaN,95840,GERENTE DE ZONA TIENDA,93783205.0,93783205.0,Cesar Jesus Francisc Reyna Salazar,NaN,NaN,MONTERREY,AUXILIAR DE INVENTARIOS
2844818,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,NaN,95883,GERENTE DE ZONA TIENDA,90042565.0,90042565.0,Cesar Humberto Favela Valenzuela,NaN,NaN,CULIACAN,AUXILIAR DE INVENTARIOS
2844819,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,NaN,132825,JEFE DE ACTIVACION DE MOTOS,90041601.0,90041601.0,Paulina Arriaga Cruz,NaN,NaN,TOLUCA,MECANICO DE MOTOS

In [64]:
full_gcp_core_sheet[full_gcp_core_sheet["numEmpleado"] == 92109391]

,Fecha de inicio de vigencia,Fecha de cierre,Estado,Estado Contratación,Posición presupuestada,Importe,Centro de costos,Centro,Ubicación,Región,...,Tipo de Trabajador,Codigo de posición principal,Nombre de posición principal,Número de persona del manager,Número de trabajador del manager,Nombre del manager,Número de Persona,Nombre Completo,Unnamed: 43,Unnamed: 44
90579,2025-05-09,NaN,Activa,Aprobada,Sí,$1.00,007 - COBRANZAS,501102,MX-03-BC-62 - C11-MEXICALI II-62,MEXICALI,...,Colaborador,2521,GERENTE DE ZONA DE COBRANZA,95578927.0,95578927.0,Martin Ernesto Corona Garcia,NaN,NaN,MEXICALI,GERENTE DE OPERACION COBRANZA

In [65]:
full_gcp_core_sheet[full_gcp_core_sheet["numEmpleado"] == 92109391]["Nombre del colaborador"]

90579    Elizabeth Arlin Jimenez Morales
Name: Nombre del colaborador, dtype: object

In [66]:
full_gcp_core_sheet["Fecha de inicio de vigencia"]

0        2025-09-08
1        2025-09-08
2        2025-09-08
3        2025-09-08
4        2025-09-08
            ...
199594   2025-04-25
199595   2025-04-25
199596   2025-04-25
199597   2025-04-25
199598   2025-04-25
Name: Fecha de inicio de vigencia, Length: 199599, dtype: datetime64[ns]

# get some turnover numbers...

In [67]:
# get turnover numbers w functions...

# obtener numero de empleados en promedio por mes, semestral y anualmente...
# turnover = num_empl_seps / av_num_empl * 100
# av_num_empl =

# obtener numero de empleados que dan de baja por mes, semestre y año


# get turnover for each case... voluntary turnover, involuntary turnover, turnover by department/role/manager/tenure

# ACTIONS:
# 1. get turnover for each person
# 2. divide by department/role/manager/tenure
# 3. get overall turnover for specific department/role/manager/tenure and timeframe
# 4. compare and get graphs...

In [70]:
employee_counts = (
    full_gcp_core_sheet
    .groupby("Número de trabajador del manager")
    .size()
    .to_dict()
)

gcp_core_sheet["empl_count"] = gcp_core_sheet["numEmpleado"].map(employee_counts).fillna(0).astype(int)

In [71]:
gcp_core_sheet

,P1_n_0,P1_n_1,P1_n_2,P1_n_3,P1_n_4,P1_n_5,P1_n_6,P1_n_7,P1_n_8,P1_n_9,...,Codigo de posición principal,Nombre de posición principal,Número de persona del manager,Número de trabajador del manager,Nombre del manager,Número de Persona,Nombre Completo,Unnamed: 43,Unnamed: 44,empl_count
0,0.045477,0.040022,0.607325,0.037355,0.035648,0.053731,0.038457,0.048750,0.043515,0.049721,...,96406,GERENTE DE ZONA TIENDA,92121438.0,92121438.0,Sebastian Cruz Alvarado,NaN,NaN,TECAMAC,GERENTE DE TIENDA MUEBLES,20
1,0.151717,0.150014,0.052267,0.011673,0.011139,0.016790,0.012017,0.015233,0.426117,0.153033,...,2521,GERENTE DE ZONA DE COBRANZA,95578927.0,95578927.0,Martin Ernesto Corona Garcia,NaN,NaN,MEXICALI,GERENTE DE OPERACION COBRANZA,50
2,0.019601,0.017250,0.261728,0.016100,0.015364,0.212832,0.016575,0.400365,0.018755,0.021430,...,2589,GERENTE DE ZONA DE COBRANZA,90373031.0,90373031.0,Joel Cesar Medina Helguera,NaN,NaN,CD JUAREZ,GERENTE DE OPERACION COBRANZA,4
3,0.024189,0.021287,0.320690,0.019869,0.254365,0.028579,0.020455,0.025942,0.258178,0.026446,...,94558,GERENTE DE ZONA TIENDA,94012131.0,94012131.0,Javier Vargas Bedolla,NaN,NaN,TOLUCA,GERENTE DE TIENDA ROPA,9
4,0.031580,0.027792,0.116152,0.025943,0.024755,0.037311,0.026705,0.645017,0.030217,0.034527,...,97399,GERENTE DE ZONA TIENDA,91490782.0,91490782.0,Edgar Isaac Mogica Betancourt,NaN,NaN,TEXCOCO,GERENTE DE TIENDA MOTOS,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2844815,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,97469,GERENTE DE ZONA TIENDA,95742948.0,95742948.0,Martha Ramirez Jimenez,NaN,NaN,OAXACA,AUXILIAR DE INVENTARIOS,0
2844816,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,95452,ENTRENAMIENTO ZONA,100093675.0,90461795.0,Reyna Karina Sanchez Rodriguez,NaN,NaN,AZCAPOTZALCO,AUXILIAR DE INVENTARIOS,0
2844817,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,95840,GERENTE DE ZONA TIENDA,93783205.0,93783205.0,Cesar Jesus Francisc Reyna Salazar,NaN,NaN,MONTERREY,AUXILIAR DE INVENTARIOS,0
2844818,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,95883,GERENTE DE ZONA TIENDA,90042565.0,90042565.0,Cesar Humberto Favela Valenzuela,NaN,NaN,CULIACAN,AUXILIAR DE INVENTARIOS,0
2844819,0.401889,0.014501,0.262981,0.013533,0.222253,0.019466,0.013933,0.017664,0.015766,0.018014,...,132825,JEFE DE ACTIVACION DE MOTOS,90041601.0,90041601.0,Paulina Arriaga Cruz,NaN,NaN,TOLUCA,MECANICO DE MOTOS,0

In [72]:
## set topic names
import pickle
file_path = "../modelo/topic_names.pkl"
with open(file_path, "rb") as f:
        colss = pickle.load(f)
colss
for idx, tupp in enumerate(zip(gcp_core_sheet.columns[:120], colss)):
  colss[idx] = tupp[0]+"_"+tupp[1]
for col in gcp_core_sheet.columns[120:]:
  colss.append(col)
gcp_core_sheet.columns = colss

# garbage

In [73]:
from dateutil.relativedelta import relativedelta
today = datetime.today()

In [74]:

current_datetime = datetime.now()

# Calculate the first day of the current month
# By setting 'day=1', you explicitly set the day component to the first of the month.
first_day_of_month = current_datetime + relativedelta(day=1)

In [75]:
for i in range(12):
  print(current_datetime + relativedelta(month=(i+1), day=1), current_datetime + relativedelta(month=(i+1), day=31))

2025-01-01 17:12:20.696799 2025-01-31 17:12:20.696799
2025-02-01 17:12:20.696799 2025-02-28 17:12:20.696799
2025-03-01 17:12:20.696799 2025-03-31 17:12:20.696799
2025-04-01 17:12:20.696799 2025-04-30 17:12:20.696799
2025-05-01 17:12:20.696799 2025-05-31 17:12:20.696799
2025-06-01 17:12:20.696799 2025-06-30 17:12:20.696799
2025-07-01 17:12:20.696799 2025-07-31 17:12:20.696799
2025-08-01 17:12:20.696799 2025-08-31 17:12:20.696799
2025-09-01 17:12:20.696799 2025-09-30 17:12:20.696799
2025-10-01 17:12:20.696799 2025-10-31 17:12:20.696799
2025-11-01 17:12:20.696799 2025-11-30 17:12:20.696799
2025-12-01 17:12:20.696799 2025-12-31 17:12:20.696799

In [76]:
first_day_of_month

datetime.datetime(2025, 10, 1, 17, 12, 20, 696799)

In [77]:
today + relativedelta(years=1)

datetime.datetime(2026, 10, 16, 17, 12, 17, 770189)

In [78]:
sum(map(lambda x: x, range(10)))

45

In [79]:
def is_date_in_range(target_date, start, end):
    diff_from_start = target_date - start
    diff_to_end = end - target_date
    return int(diff_from_start.days >= 0 and diff_to_end.days >= 0)

def turnover_rate(df, start, end):
  seps = sum(map(lambda y_dt: is_date_in_range(y_dt, start, end), df[df["Estado"]=="Inactiva"]["Fecha de inicio de vigencia"]))
  A_employees = sum(map(lambda y_dt: y_dt <= start, df["Fecha de inicio de vigencia"]))
  B_employees = sum(map(lambda y_dt: y_dt <= end, df["Fecha de inicio de vigencia"]))
  return A_employees / B_employees * 100

In [ ]:
# adjuntar
# Region SSFF, Centro de costos, ciudad, #Centro, Puesto

In [80]:
gcp_core_sheet.columns[:120]

Index(['P1_n_0_compromiso_y_responsabilidad',
       'P1_n_1_beneficios_y_valores_de_la_empresa',
       'P1_n_2_prestaciones_y_sueldo', 'P1_n_3_buen_ambiente_laboral',
       'P1_n_4_oportunidades_de_desarrollo_y_crecimiento',
       'P1_n_5_satisfaccion_y_gusto_por_el_trabajo',
       'P1_n_6_crecimiento_y_estabilidad_laboral',
       'P1_n_7_estabilidad_y_seguridad_laboral',
       'P1_n_8_identificacion_con_la_empresa_y_balance',
       'P1_n_9_buen_trato_y_apoyo',
       ...
       'P6_v_0_falta_de_oportunidades_de_desarrollo_y_pago',
       'P6_v_1_falta_de_atencion_de_los_jefes_al_colaborador',
       'P6_v_2_consideraciones_sobre_el_trabajo_y_el_personal',
       'P6_v_3_comparativa_de_sueldos_y_puestos_con_otras_empresas',
       'P6_v_4_rol_de_los_gerentes_en_el_clima_laboral',
       'P6_v_5_falta_de_oportunidades_a_largo_plazo',
       'P6_v_6_carga_de_trabajo_y_metas_vs_incentivos',
       'P6_v_7_necesidad_de_mejorar_condiciones_para_el_bienestar',
       'P6_v_8_insatisfaccion_general_con_el_sueldo',
       'P6_v_9_percepciones_personales_sobre_la_empresa'],
      dtype='object', length=120)

In [81]:
list(gcp_core_sheet.columns)

['P1_n_0_compromiso_y_responsabilidad',
 'P1_n_1_beneficios_y_valores_de_la_empresa',
 'P1_n_2_prestaciones_y_sueldo',
 'P1_n_3_buen_ambiente_laboral',
 'P1_n_4_oportunidades_de_desarrollo_y_crecimiento',
 'P1_n_5_satisfaccion_y_gusto_por_el_trabajo',
 'P1_n_6_crecimiento_y_estabilidad_laboral',
 'P1_n_7_estabilidad_y_seguridad_laboral',
 'P1_n_8_identificacion_con_la_empresa_y_balance',
 'P1_n_9_buen_trato_y_apoyo',
 'P1_v_0_compromiso_y_lealtad',
 'P1_v_1_oferta_de_prestaciones_de_la_empresa',
 'P1_v_2_necesidad_de_un_trabajo_estable',
 'P1_v_3_compensacion_y_condiciones_laborales',
 'P1_v_4_satisfaccion_con_el_trabajo',
 'P1_v_5_ambiente_y_desarrollo_laboral',
 'P1_v_6_apoyo_de_la_empresa_a_colaboradores',
 'P1_v_7_comodidad_y_beneficios_adicionales',
 'P1_v_8_oportunidades_de_crecimiento_y_beneficios',
 'P1_v_9_estabilidad_y_seguridad_laboral',
 'P2_n_0_busqueda_de_mejores_condiciones_laborales',
 'P2_n_1_desadaptacion_al_ritmo_de_trabajo',
 'P2_n_2_problemas_con_horarios_y_jefes',
 'P2_n_3_insatisfaccion_con_las_actividades',
 'P2_n_4_exceso_de_carga_de_trabajo_y_exigencia',
 'P2_n_5_falta_de_compromiso_y_adaptacion',
 'P2_n_6_sueldo_bajo_y_horarios_demandantes',
 'P2_n_7_expectativas_incumplidas_sobre_pago_y_jornada',
 'P2_n_8_mal_trato_y_falta_de_seguimiento_de_lideres',
 'P2_n_9_falta_de_adaptacion_al_ritmo_de_la_empresa',
 'P2_v_0_busqueda_de_mejores_oportunidades_y_ambiente',
 'P2_v_1_mal_trato_y_baja_compensacion',
 'P2_v_2_insatisfaccion_con_tareas_asignadas',
 'P2_v_3_falta_de_adaptacion_y_gusto_por_el_trabajo',
 'P2_v_4_exceso_de_carga_y_ritmo_de_trabajo',
 'P2_v_5_falta_de_liderazgo_y_seguimiento',
 'P2_v_6_mejores_ofertas_salariales_y_prestaciones',
 'P2_v_7_desmotivacion_por_metas_y_falta_de_adaptacion',
 'P2_v_8_horarios_extensos_y_expectativas_no_cumplidas',
 'P2_v_9_conflicto_entre_horarios_y_responsabilidades_personales',
 'P3_n_0_busqueda_de_mejores_condiciones_laborales',
 'P3_n_1_desgaste_y_cambio_generacional',
 'P3_n_2_conflictos_con_jefes_y_horarios',
 'P3_n_3_insatisfaccion_con_las_tareas_y_responsabilidades',
 'P3_n_4_exceso_de_carga_de_trabajo_y_presion',
 'P3_n_5_perdida_de_compromiso_y_responsabilidad',
 'P3_n_6_sueldo_poco_competitivo_y_malos_horarios',
 'P3_n_7_expectativas_economicas_no_cumplidas',
 'P3_n_8_mal_trato_por_parte_de_lideres',
 'P3_n_9_falta_de_adaptacion_a_cambios_en_el_trabajo',
 'P3_v_0_busqueda_de_mejores_oportunidades_laborales',
 'P3_v_1_mejor_oferta_salarial_y_de_trato',
 'P3_v_2_rutina_y_falta_de_nuevos_retos',
 'P3_v_3_perdida_de_interes_y_desadaptacion',
 'P3_v_4_exceso_de_carga_y_ritmo_de_trabajo',
 'P3_v_5_mal_liderazgo_y_falta_de_compromiso',
 'P3_v_6_ofertas_con_mejor_sueldo_y_prestaciones',
 'P3_v_7_desgaste_y_desmotivacion_por_metas',
 'P3_v_8_horarios_extensos_y_desgaste_laboral',
 'P3_v_9_conflicto_entre_horarios_y_vida_personal',
 'P4_n_0_alta_competencia_laboral_en_la_zona',
 'P4_n_1_cultura_de_alta_exigencia_y_metas',
 'P4_n_2_caracteristicas_especificas_de_la_zona',
 'P4_n_3_poca_afluencia_de_clientes_e_inseguridad',
 'P4_n_4_falta_de_personal_comprometido_por_mejores_ofertas',
 'P4_n_5_ubicacion_y_formato_de_la_tienda',
 'P4_n_6_inseguridad_y_riesgo_de_robo',
 'P4_n_7_reto_de_liderar_colaboradores',
 'P4_n_8_falta_de_personal_y_cambios_organizacionales',
 'P4_n_9_entorno_competitivo_y_carga_de_trabajo',
 'P4_v_0_competencia_por_talento_con_mejores_condiciones',
 'P4_v_1_condiciones_de_inseguridad_del_entorno',
 'P4_v_2_poca_afluencia_de_clientes_y_carga_de_trabajo',
 'P4_v_3_tipo_de_clientela_y_ubicacion_de_la_tienda',
 'P4_v_4_cultura_orientada_a_metas_de_venta',
 'P4_v_5_falta_de_personal_y_problemas_de_seguridad',
 'P4_v_6_problemas_de_seguridad_y_transporte',
 'P4_v_7_alta_oferta_laboral_en_la_zona',
 'P4_v_8_ambiente_laboral_y_demanda_de_clientes',
 'P4_v_9_gestion_de_colaboradores_y_cambio',
 'P5_n_0_mejores_salarios_e_incentivos',
 'P5_n_1_gestion_de_personal_y_carga_de_trabajo',
 'P5_n_2_mejores_herramientas_y_horarios',
 'P5_n_3_trabajo_en_equipo_y_apoyo',
 'P5_n_4_mejora_del_ambiente_laboral_y_liderazgo',
 'P5_n_5_aumento_de_sueldo_y_apoyo_de_transporte',
 'P5_n_6_mejores_sueldos_y_horarios_flexibles',
 'P5_n_7_planes_de_desarrollo_y_seguimiento',
 'P5_n_8_mejora_del_esquema_de_incentivos_y_metas',
 'P5_n_9_mejores_prestaciones_y_beneficios',
 'P5_v_0_esquemas_de_incentivos_y_metas_alcanzables',
 'P5_v_1_mejora_de_sueldos_y_horarios',
 'P5_v_2_mejora_de_prestaciones_y_ambiente_laboral',
 'P5_v_3_gestion_de_la_carga_de_trabajo',
 'P5_v_4_planes_de_seguimiento_y_desarrollo',
 'P5_v_5_apoyo_al_personal_y_transporte',
 'P5_v_6_apoyo_individualizado_por_parte_de_gerentes',
 'P5_v_7_bienestar_del_colaborador',
 'P5_v_8_mejores_sueldos_y_flexibilidad_de_jornada',
 'P5_v_9_atencion_a_las_necesidades_del_colaborador',
 'P6_n_0_impacto_de_los_gerentes_en_el_ambiente_laboral',
 'P6_n_1_necesidad_de_mejorar_sueldos_y_trato',
 'P6_n_2_factores_personales_en_la_decision_de_salida',
 'P6_n_3_falta_de_personal_para_cumplir_metas',
 'P6_n_4_excesiva_carga_de_trabajo',
 'P6_n_5_opinion_sobre_la_gestion_gerencial',
 'P6_n_6_problematica_de_horarios_y_jornadas',
 'P6_n_7_pago_de_horas_extra_y_descansos',
 'P6_n_8_falta_de_incentivos_y_crecimiento',
 'P6_n_9_insatisfaccion_con_sueldos_e_incentivos',
 'P6_v_0_falta_de_oportunidades_de_desarrollo_y_pago',
 'P6_v_1_falta_de_atencion_de_los_jefes_al_colaborador',
 'P6_v_2_consideraciones_sobre_el_trabajo_y_el_personal',
 'P6_v_3_comparativa_de_sueldos_y_puestos_con_otras_empresas',
 'P6_v_4_rol_de_los_gerentes_en_el_clima_laboral',
 'P6_v_5_falta_de_oportunidades_a_largo_plazo',
 'P6_v_6_carga_de_trabajo_y_metas_vs_incentivos',
 'P6_v_7_necesidad_de_mejorar_condiciones_para_el_bienestar',
 'P6_v_8_insatisfaccion_general_con_el_sueldo',
 'P6_v_9_percepciones_personales_sobre_la_empresa',
 'numEmpleado',
 'Fecha de inicio de vigencia',
 'Fecha de cierre',
 'Estado',
 'Estado Contratación',
 'Posición presupuestada',
 'Importe',
 'Centro de costos',
 'Centro',
 'Ubicación',
 'Región',
 'Ciudad',
 'Empleador legal',
 'Unidad de negocio',
 'División',
 'Departamento',
 'Código de puesto',
 'Nombre de puesto',
 'Familia de puesto',
 'Función del puesto',
 'Código de posición',
 'Nombre de posición',
 'Indefinido o temporal',
 'Tipo de presupuesto ',
 'Categoria de asignación',
 'Plantilla Autorizada',
 'Plantilla Activa',
 'Vacantes',
 'Grupo salarial',
 'Rol de contribución',
 'Número de persona',
 'Nombre del colaborador',
 'Fecha de antigüedad Grupo',
 'Fecha de contratación empleador legal actual',
 'Fecha de entrada en posición actual',
 'Tipo de Trabajador',
 'Codigo de posición principal',
 'Nombre de posición principal',
 'Número de persona del manager',
 'Número de trabajador del manager',
 'Nombre del manager',
 'Número de Persona',
 'Nombre Completo',
 'Unnamed: 43',
 'Unnamed: 44',
 'empl_count']

In [82]:
gcp_core_tabla_dinamica = pd.read_csv("../data/GCP_Core_Plantilla_ActivaVSAutorizada_REP_8_Tabla_dinámica_1.csv")
gcp_core_tabla_dinamica

,Región,Centro de costos,Nombre de puesto,Número de trabajador,Nombre del colaborador,Unnamed: 5,Unnamed: 6,Estatus,Unnamed: 8
0,AZCAPOTZALCO,001 - TDAS MUEBLES,GERENTE DE TIENDA MUEBLES,90038989.0,Adrian Hernandez Barrientos,NaN,"90,038,989.00",Realizado,GERENTE DE ZONA TIENDA
1,AZCAPOTZALCO,NaN,GERENTE DE TIENDA MUEBLES,90064636.0,Francisco Pacheco Torres,NaN,"90,064,636.00",Realizado,GERENTE DE ZONA TIENDA
2,AZCAPOTZALCO,NaN,GERENTE DE TIENDA MUEBLES,90077313.0,Tania Itzel Pina Loo,NaN,"90,077,313.00",Realizado,GERENTE DE ZONA TIENDA
3,AZCAPOTZALCO,NaN,GERENTE DE TIENDA MUEBLES,90157290.0,Hector Mejia Gutierrez,NaN,"90,157,290.00",Realizado,GERENTE DE ZONA TIENDA
4,AZCAPOTZALCO,NaN,GERENTE DE TIENDA MUEBLES,90214893.0,Julio Cesar Ceron Fonseca,NaN,"90,214,893.00",Realizado,GERENTE DE ZONA TIENDA
...,...,...,...,...,...,...,...,...,...
3802,VILLAHERMOSA,NaN,GERENTE DE TIENDA MOTOS,97197602.0,German Vidal Hernandez,NaN,"97,197,602.00",Realizado,GERENTE DE ZONA TIENDA
3803,VILLAHERMOSA,NaN,GERENTE DE TIENDA MOTOS,98655299.0,Gerardo Ruiz Hernandez,NaN,"98,655,299.00",Realizado,GERENTE DE ZONA TIENDA
3804,VILLAHERMOSA,NaN,GERENTE DE TIENDA MOTOS,98720015.0,Liborio Lezama Alcantara,NaN,"98,720,015.00",Realizado,GERENTE DE ZONA TIENDA
3805,Total VILLAHERMOSA,NaN,NaN,NaN,NaN,NaN,NaN,Realizado,NaN
3806,Suma total,NaN,NaN,NaN,NaN,NaN,NaN,Realizado,NaN

In [84]:
def print_topics(topics):
  for topic_id, topic_words in topics:
    # topic_words is a string like '0.050*"word1" + 0.040*"word2" ...'
    print(f"Topic #{topic_id}: {topic_words}")
  return None

top_dict = pd.read_pickle("../modelo/topics_dict.pkl")
top_dict

,P1_n,P1_v,P2_n,P2_v,P3_n,P3_v,P4_n,P4_v,P5_n,P5_v,P6_n,P6_v
0,"(0, 0.167*""compromiso"" + 0.098*""responsabilida...","(0, 0.164*""compromiso"" + 0.100*""empresa"" + 0.0...","(0, 0.264*""laboral"" + 0.093*""mejores"" + 0.086*...","(0, 0.152*""laboral"" + 0.083*""ambiente"" + 0.060...","(0, 0.264*""laboral"" + 0.093*""mejores"" + 0.086*...","(0, 0.152*""laboral"" + 0.083*""ambiente"" + 0.060...","(0, 0.048*""tiendas"" + 0.048*""competencia"" + 0....","(0, 0.074*""competencia"" + 0.048*""horarios"" + 0...","(0, 0.067*""mayor"" + 0.063*""planta"" + 0.053*""sa...","(0, 0.254*""incentivos"" + 0.076*""metas"" + 0.054...","(0, 0.065*""gerentes"" + 0.053*""laboral"" + 0.050...","(0, 0.101*""ninguno"" + 0.093*""preguntas"" + 0.06..."
1,"(1, 0.329*""empresa"" + 0.242*""beneficios"" + 0.0...","(1, 0.261*""prestaciones"" + 0.232*""empresa"" + 0...","(1, 0.090*""empresa"" + 0.089*""trabajar"" + 0.052...","(1, 0.099*""empresa"" + 0.057*""salario"" + 0.044*...","(1, 0.090*""empresa"" + 0.089*""trabajar"" + 0.052...","(1, 0.099*""empresa"" + 0.057*""salario"" + 0.044*...","(1, 0.141*""metas"" + 0.061*""cultura"" + 0.060*""l...","(1, 0.080*""cada"" + 0.072*""condiciones"" + 0.051...","(1, 0.052*""colaboradores"" + 0.038*""trabajo"" + ...","(1, 0.155*""mejorar"" + 0.097*""horario"" + 0.089*...","(1, 0.081*""sueldo"" + 0.066*""colaboradores"" + 0...","(1, 0.068*""momento"" + 0.045*""empresa"" + 0.037*..."
2,"(2, 0.716*""prestaciones"" + 0.093*""empresa"" + 0...","(2, 0.188*""necesidad"" + 0.094*""trabajo"" + 0.07...","(2, 0.261*""horarios"" + 0.045*""personales"" + 0....","(2, 0.074*""actividades"" + 0.045*""colaboradores...","(2, 0.261*""horarios"" + 0.045*""personales"" + 0....","(2, 0.074*""actividades"" + 0.045*""colaboradores...","(2, 0.062*""ciudad"" + 0.046*""centro"" + 0.041*""d...","(2, 0.153*""clientes"" + 0.130*""afluencia"" + 0.0...","(2, 0.075*""personal"" + 0.032*""herramientas"" + ...","(2, 0.274*""prestaciones"" + 0.105*""laboral"" + 0...","(2, 0.045*""colaborador"" + 0.035*""empresa"" + 0....","(2, 0.041*""trabajo"" + 0.035*""colaboradores"" + ..."
3,"(3, 0.379*""laboral"" + 0.316*""ambiente"" + 0.124...","(3, 0.718*""prestaciones"" + 0.068*""sueldo"" + 0....","(3, 0.099*""gusta"" + 0.092*""actividades"" + 0.04...","(3, 0.127*""gusta"" + 0.116*""trabajo"" + 0.112*""r...","(3, 0.099*""gusta"" + 0.092*""actividades"" + 0.04...","(3, 0.127*""gusta"" + 0.116*""trabajo"" + 0.112*""r...","(3, 0.240*""clientes"" + 0.142*""afluencia"" + 0.0...","(3, 0.087*""clientes"" + 0.068*""tienda"" + 0.054*...","(3, 0.038*""persona"" + 0.038*""empresa"" + 0.036*...","(3, 0.198*""trabajo"" + 0.043*""planta"" + 0.038*""...","(3, 0.049*""metas"" + 0.044*""falta"" + 0.042*""per...","(3, 0.053*""sueldos"" + 0.046*""ser"" + 0.045*""mej..."
4,"(4, 0.141*""ofrece"" + 0.131*""empresa"" + 0.116*""...","(4, 0.325*""trabajo"" + 0.148*""gusta"" + 0.074*""g...","(4, 0.232*""trabajo"" + 0.106*""carga"" + 0.073*""e...","(4, 0.240*""trabajo"" + 0.090*""carga"" + 0.058*""p...","(4, 0.232*""trabajo"" + 0.106*""carga"" + 0.073*""e...","(4, 0.240*""trabajo"" + 0.090*""carga"" + 0.058*""p...","(4, 0.125*""falta"" + 0.092*""colaboradores"" + 0....","(4, 0.153*""metas"" + 0.067*""cultura"" + 0.034*""v...","(4, 0.115*""laboral"" + 0.066*""colaborador"" + 0....","(4, 0.164*""seguimiento"" + 0.061*""desarrollo"" +...","(4, 0.166*""trabajo"" + 0.052*""carga"" + 0.032*""v...","(4, 0.084*""gerentes"" + 0.062*""colaboradores"" +..."
5,"(5, 0.446*""trabajo"" + 0.169*""gusta"" + 0.082*""g...","(5, 0.281*""laboral"" + 0.231*""ambiente"" + 0.142...","(5, 0.328*""falta"" + 0.105*""compromiso"" + 0.102...","(5, 0.380*""falta"" + 0.089*""compromiso"" + 0.056...","(5, 0.328*""falta"" + 0.105*""compromiso"" + 0.102...","(5, 0.380*""falta"" + 0.089*""compromiso"" + 0.056...","(5, 0.180*""tienda"" + 0.105*""zona"" + 0.073*""gen...","(5, 0.140*""personal"" + 0.045*""farderos"" + 0.03...","(5, 0.184*""sueldo"" + 0.080*""apoyo"" + 0.073*""tr...","(5, 0.078*""personal"" + 0.065*""apoyo"" + 0.061*""...","(5, 0.046*""considero"" + 0.030*""creo"" + 0.029*""...","(5, 0.073*""tiempo"" + 0.034*""colaboradores"" + 0..."
6,"(6, 0.236*""crecimiento"" + 0.131*""oportunidades...","(6, 0.148*""empresa"" + 0.129*""brinda"" + 0.093*""...","(6, 0.326*""horario"" + 0.257*""sueldo"" + 0.039*""...","(6, 0.150*""sueldo"" + 0.081*""tiempo"" + 0.063*""l...","(6, 0.326*""horario"" + 0.257*""sueldo"" + 0.039*""...","(6, 0.150*""sueldo"" + 0.081*""tiempo"" + 0.063*""l...","(6, 0.052*""colaborador"" + 0.048*""farderos"" + 0...","(6, 0.183*""falta"" + 0.154*""tienda"" + 0.073*""pe...","(6, 0.189*""horarios"" + 0.094*""sueldos"" + 0.062...","(6, 0.078*""colaborador"" + 0.045*""cada"" + 0.032...","(6, 0.111*""horarios"" + 0.108*""tiempo"" + 0.098*...","(6, 0.131*""trabajo"" + 0.076*""incentivos"" + 0.0..."
7,"(7, 0.440*""estabilidad"" + 0.163*""laboral"" + 0....","(7, 0.075*""comodidad"" + 0.074*""colaborador"" + ...","(7, 0.181*""tiempo"" + 0.072*""pago"" + 0.057*""lab...","(7, 0.097*""metas"" + 0.092*""trabajar"" + 0.063*""...","(7, 0.181*""tiempo"" + 0.072*""pago"" + 0.057*""lab...","(7, 0.097*""metas"" + 0.092*""trabajar"" + 0.063*""...","(7, 0.050*""cada"" + 0.043*""ser"" + 0.041*""centro...","(7, 0.091*""zona"" + 0.085*""gente"" + 0.052*""much...","(7, 0.206*""seguimiento"" + 0.077*""desarrollo"" +...","(7, 0.089*""empresa"" + 0.064*""bien"" + 0.035*""pe...","(7, 0.038*""comentarios"" + 0.038*""horas"" + 0.03...","(7, 0.171*""bien"" + 0.097*""horarios"" + 0.053*""m..."
8,"(8, 0.169*""coppel"" + 0.118*""empresa"" + 0.061*""...","(8, 0.208*""crecimiento"" + 0.153*""beneficios"" +...","(8, 0.082*""falta"" + 0.058*""parte"" + 0.047*""seg...","(8, 0.297*""horario"" + 0.050*""trabajo"" + 0.041*...","(8, 0.082*""falta"" + 0.058*""parte"" + 0.047*""seg...","(8, 0.297*""horario"" + 0.050*""trabajo"" + 0.041*...","(8, 0.217*""personal"" + 0.069*""falta"" + 0.027*""...","(8, 0.077*""laboral"" + 0.044*""personal"" + 0.037...","(8, 0.236*""incentivos"" + 0.055*""metas"" + 0.030...","(8, 0.210*""horarios"" + 0.122*""sueldo"" + 0.057*...","(8, 0.213*""bien"" + 0.142*""incentivos"" + 0.094*...","(8, 0.159*""sueldo"" + 0.153*""ninguna"" + 0.056*""..."
9,"(9, 0.165*""necesidad"" + 0.111*""trato"" + 0.065*...","(9, 0.510*""estabilidad"" + 0.174*""laboral"" + 0....","(9, 0.103*""trabajo"" + 0.055*""adaptan"" + 0.046*...","(9, 0.266*""horarios"" + 0.061*""personales"" + 0....","(9, 0.103*""trabajo"" + 0.055*""adaptan"" + 0.046*...","(9, 0.266*""horarios"" + 0.061*""personales"" + 0....","(9, 0.160*""trabajo"" + 0.042*""entorno"" + 0.039*...","(9, 0.112*""colaboradores"" + 0.041*""centro"" + 0...","(9, 0.322*""prestaciones"" + 0.054*""pago"" + 0.03...","(9, 0.037*""manera"" + 0.029*""tiempo"" + 0.028*""m...","(9, 0.228*""ninguna"" + 0.093*""sueldos"" + 0.073*...","(9, 0.100*""creo"" + 0.068*""horario"" + 0.045*""em..."

In [85]:
for col in top_dict:
  print("column:", col)
  print_topics(top_dict[col].tolist())

column: P1_n
Topic #0: 0.167*"compromiso" + 0.098*"responsabilidad" + 0.082*"empresa" + 0.044*"cambios" + 0.042*"comodidad" + 0.041*"resultados" + 0.039*"tener" + 0.035*"cambio" + 0.034*"procesos" + 0.032*"actividades"
Topic #1: 0.329*"empresa" + 0.242*"beneficios" + 0.094*"valores" + 0.077*"colaboradores" + 0.036*"otorga" + 0.031*"bien" + 0.028*"hacer" + 0.022*"encuentran" + 0.020*"pertenencia" + 0.019*"gran"
Topic #2: 0.716*"prestaciones" + 0.093*"empresa" + 0.050*"sueldo" + 0.050*"buenas" + 0.018*"utilidades" + 0.013*"incentivos" + 0.010*"buenos" + 0.008*"jefes" + 0.007*"excelentes" + 0.006*"cuenta"
Topic #3: 0.379*"laboral" + 0.316*"ambiente" + 0.124*"buen" + 0.046*"prestaciones" + 0.017*"ingreso" + 0.016*"facilidad" + 0.016*"vida" + 0.012*"manera" + 0.012*"calidad" + 0.011*"forma"
Topic #4: 0.141*"ofrece" + 0.131*"empresa" + 0.116*"desarrollo" + 0.074*"dentro" + 0.052*"crecimiento" + 0.044*"coppel" + 0.030*"cultura" + 0.028*"misma" + 0.028*"oportunidad" + 0.024*"seguir"
Topic #5: 0.446*"trabajo" + 0.169*"gusta" + 0.082*"gusto" + 0.054*"hacen" + 0.030*"buen" + 0.028*"sienten" + 0.025*"necesidades" + 0.025*"horario" + 0.022*"equipo" + 0.014*"realizan"
Topic #6: 0.236*"crecimiento" + 0.131*"oportunidades" + 0.084*"estable" + 0.068*"oportunidad" + 0.065*"clima" + 0.042*"salario" + 0.039*"zona" + 0.038*"falta" + 0.037*"lealtad" + 0.036*"empleo"
Topic #7: 0.440*"estabilidad" + 0.163*"laboral" + 0.079*"empresa" + 0.050*"personal" + 0.050*"desarrollo" + 0.047*"seguridad" + 0.038*"profesional" + 0.028*"crecimiento" + 0.017*"brinda" + 0.015*"seguro"
Topic #8: 0.169*"coppel" + 0.118*"empresa" + 0.061*"buena" + 0.061*"persona" + 0.052*"brinda" + 0.039*"grupo" + 0.037*"tiempo" + 0.035*"familia" + 0.032*"horarios" + 0.031*"empresas"
Topic #9: 0.165*"necesidad" + 0.111*"trato" + 0.065*"trabajar" + 0.054*"ser" + 0.044*"buen" + 0.042*"puesto" + 0.036*"colaborador" + 0.036*"persona" + 0.034*"apoyo" + 0.030*"parte"
column: P1_v
Topic #0: 0.164*"compromiso" + 0.100*"empresa" + 0.097*"responsabilidad" + 0.069*"trabajar" + 0.047*"lealtad" + 0.047*"puesto" + 0.046*"resultados" + 0.030*"metas" + 0.026*"cumplir" + 0.025*"confianza"
Topic #1: 0.261*"prestaciones" + 0.232*"empresa" + 0.125*"coppel" + 0.084*"buenas" + 0.077*"ofrece" + 0.043*"buena" + 0.032*"grupo" + 0.028*"jefes" + 0.019*"otorga" + 0.017*"parte"
Topic #2: 0.188*"necesidad" + 0.094*"trabajo" + 0.071*"estable" + 0.066*"tener" + 0.047*"necesidades" + 0.046*"cambios" + 0.041*"apoyo" + 0.040*"familia" + 0.032*"falta" + 0.031*"zona"
Topic #3: 0.718*"prestaciones" + 0.068*"sueldo" + 0.066*"trato" + 0.025*"incentivos" + 0.020*"horarios" + 0.017*"buen" + 0.016*"horario" + 0.016*"humano" + 0.011*"domicilio" + 0.009*"cumplimiento"
Topic #4: 0.325*"trabajo" + 0.148*"gusta" + 0.074*"gusto" + 0.056*"empresa" + 0.047*"hacen" + 0.038*"personas" + 0.037*"sienten" + 0.035*"buen" + 0.025*"actividades" + 0.024*"edad"
Topic #5: 0.281*"laboral" + 0.231*"ambiente" + 0.142*"prestaciones" + 0.095*"buen" + 0.072*"desarrollo" + 0.055*"personal" + 0.031*"profesional" + 0.018*"jefe" + 0.018*"hacer" + 0.012*"sentirse"
Topic #6: 0.148*"empresa" + 0.129*"brinda" + 0.093*"colaboradores" + 0.046*"vida" + 0.046*"coppel" + 0.042*"persona" + 0.033*"laborales" + 0.031*"cada" + 0.028*"forma" + 0.028*"seguir"
Topic #7: 0.075*"comodidad" + 0.074*"colaborador" + 0.069*"utilidades" + 0.052*"cambio" + 0.050*"procesos" + 0.049*"empresas" + 0.039*"muchas" + 0.038*"mejor" + 0.035*"empresa" + 0.033*"hacia"
Topic #8: 0.208*"crecimiento" + 0.153*"beneficios" + 0.112*"empresa" + 0.085*"oportunidades" + 0.061*"oportunidad" + 0.051*"desarrollo" + 0.048*"prestaciones" + 0.043*"valores" + 0.042*"clima" + 0.022*"dentro"
Topic #9: 0.510*"estabilidad" + 0.174*"laboral" + 0.104*"empresa" + 0.054*"seguridad" + 0.036*"salario" + 0.031*"ser" + 0.022*"puede" + 0.021*"seguro" + 0.016*"ingreso" + 0.014*"encuentran"
column: P2_n
Topic #0: 0.264*"laboral" + 0.093*"mejores" + 0.086*"ambiente" + 0.069*"jornada" + 0.046*"oportunidades" + 0.039*"ingresos" + 0.032*"sueldos" + 0.024*"semana" + 0.021*"buscan" + 0.021*"crecimiento"
Topic #1: 0.090*"empresa" + 0.089*"trabajar" + 0.052*"gusta" + 0.049*"trabajo" + 0.032*"acostumbrados" + 0.030*"vez" + 0.029*"generaciones" + 0.029*"nuevas" + 0.029*"bajo" + 0.024*"pesado"
Topic #2: 0.261*"horarios" + 0.045*"personales" + 0.041*"salario" + 0.041*"jefes" + 0.036*"mejor" + 0.030*"malos" + 0.023*"problemas" + 0.022*"tener" + 0.020*"caso" + 0.018*"procesos"
Topic #3: 0.099*"gusta" + 0.092*"actividades" + 0.040*"realizar" + 0.038*"quieren" + 0.031*"responsabilidades" + 0.031*"hacer" + 0.026*"cumplir" + 0.026*"faltantes" + 0.022*"metas" + 0.022*"faltante"
Topic #4: 0.232*"trabajo" + 0.106*"carga" + 0.073*"exigencia" + 0.063*"metas" + 0.061*"personal" + 0.019*"cumplimiento" + 0.019*"cargas" + 0.019*"mucha" + 0.016*"nivel" + 0.016*"tiendas"
Topic #5: 0.328*"falta" + 0.105*"compromiso" + 0.102*"responsabilidad" + 0.060*"puesto" + 0.024*"empresa" + 0.021*"actividades" + 0.020*"perfil" + 0.019*"adaptarse" + 0.018*"logran" + 0.017*"exigencias"
Topic #6: 0.326*"horario" + 0.257*"sueldo" + 0.039*"bajo" + 0.025*"entrenamiento" + 0.023*"mejor" + 0.022*"competitivo" + 0.020*"cobros" + 0.019*"sol" + 0.019*"presion" + 0.018*"alto"
Topic #7: 0.181*"tiempo" + 0.072*"pago" + 0.057*"laborales" + 0.050*"esperaban" + 0.049*"trabajo" + 0.041*"incentivos" + 0.035*"tienda" + 0.032*"quincenal" + 0.031*"expectativas" + 0.029*"extenso"
Topic #8: 0.082*"falta" + 0.058*"parte" + 0.047*"seguimiento" + 0.042*"empresa" + 0.039*"prestaciones" + 0.039*"gerente" + 0.036*"mala" + 0.033*"trato" + 0.030*"jefe" + 0.029*"colaborador"
Topic #9: 0.103*"trabajo" + 0.055*"adaptan" + 0.046*"ser" + 0.036*"coppel" + 0.030*"tiempo" + 0.028*"ritmo" + 0.027*"puede" + 0.026*"colaboradores" + 0.023*"forma" + 0.020*"mismo"
column: P2_v
Topic #0: 0.152*"laboral" + 0.083*"ambiente" + 0.060*"mejores" + 0.044*"oportunidades" + 0.036*"ser" + 0.035*"mal" + 0.034*"buscan" + 0.029*"ingresos" + 0.027*"factor" + 0.027*"puede"
Topic #1: 0.099*"empresa" + 0.057*"salario" + 0.044*"trato" + 0.043*"tener" + 0.034*"tiempo" + 0.030*"mejor" + 0.028*"empleo" + 0.028*"faltantes" + 0.028*"pago" + 0.025*"gerentes"
Topic #2: 0.074*"actividades" + 0.045*"colaboradores" + 0.039*"realizar" + 0.033*"solo" + 0.022*"bien" + 0.020*"ser" + 0.020*"clientes" + 0.019*"muchas" + 0.018*"hacer" + 0.016*"hoy"
Topic #3: 0.127*"gusta" + 0.116*"trabajo" + 0.112*"responsabilidad" + 0.057*"adaptan" + 0.051*"quieren" + 0.036*"generaciones" + 0.035*"nuevas" + 0.035*"empresa" + 0.025*"gusto" + 0.021*"necesidades"
Topic #4: 0.240*"trabajo" + 0.090*"carga" + 0.058*"personal" + 0.048*"exigencia" + 0.023*"tiempo" + 0.022*"menos" + 0.022*"metas" + 0.022*"incentivos" + 0.021*"vez" + 0.018*"ritmo"
Topic #5: 0.380*"falta" + 0.089*"compromiso" + 0.056*"parte" + 0.056*"seguimiento" + 0.043*"mala" + 0.036*"gerente" + 0.032*"jefes" + 0.027*"jefe" + 0.024*"malos" + 0.021*"liderazgo"
Topic #6: 0.150*"sueldo" + 0.081*"tiempo" + 0.063*"laboral" + 0.060*"jornada" + 0.052*"prestaciones" + 0.040*"sueldos" + 0.036*"esperaban" + 0.028*"empresas" + 0.026*"mejores" + 0.024*"mejor"
Topic #7: 0.097*"metas" + 0.092*"trabajar" + 0.063*"bajo" + 0.047*"acostumbrados" + 0.045*"gusta" + 0.037*"sienten" + 0.036*"adaptan" + 0.029*"trabajo" + 0.027*"cobro" + 0.026*"forma"
Topic #8: 0.297*"horario" + 0.050*"trabajo" + 0.041*"expectativas" + 0.038*"laboral" + 0.036*"poca" + 0.034*"tienda" + 0.033*"tiempo" + 0.029*"coppel" + 0.026*"extenso" + 0.026*"laborales"
Topic #9: 0.266*"horarios" + 0.061*"personales" + 0.044*"responsabilidades" + 0.042*"puesto" + 0.039*"actividades" + 0.036*"funciones" + 0.031*"temas" + 0.027*"entrevista" + 0.023*"problemas" + 0.021*"cambio"
column: P3_n
Topic #0: 0.264*"laboral" + 0.093*"mejores" + 0.086*"ambiente" + 0.069*"jornada" + 0.046*"oportunidades" + 0.039*"ingresos" + 0.032*"sueldos" + 0.024*"semana" + 0.021*"buscan" + 0.021*"crecimiento"
Topic #1: 0.090*"empresa" + 0.089*"trabajar" + 0.052*"gusta" + 0.049*"trabajo" + 0.032*"acostumbrados" + 0.030*"vez" + 0.029*"generaciones" + 0.029*"nuevas" + 0.029*"bajo" + 0.024*"pesado"
Topic #2: 0.261*"horarios" + 0.045*"personales" + 0.041*"salario" + 0.041*"jefes" + 0.036*"mejor" + 0.030*"malos" + 0.023*"problemas" + 0.022*"tener" + 0.020*"caso" + 0.018*"procesos"
Topic #3: 0.099*"gusta" + 0.092*"actividades" + 0.040*"realizar" + 0.038*"quieren" + 0.031*"responsabilidades" + 0.031*"hacer" + 0.026*"cumplir" + 0.026*"faltantes" + 0.022*"metas" + 0.022*"faltante"
Topic #4: 0.232*"trabajo" + 0.106*"carga" + 0.073*"exigencia" + 0.063*"metas" + 0.061*"personal" + 0.019*"cumplimiento" + 0.019*"cargas" + 0.019*"mucha" + 0.016*"nivel" + 0.016*"tiendas"
Topic #5: 0.328*"falta" + 0.105*"compromiso" + 0.102*"responsabilidad" + 0.060*"puesto" + 0.024*"empresa" + 0.021*"actividades" + 0.020*"perfil" + 0.019*"adaptarse" + 0.018*"logran" + 0.017*"exigencias"
Topic #6: 0.326*"horario" + 0.257*"sueldo" + 0.039*"bajo" + 0.025*"entrenamiento" + 0.023*"mejor" + 0.022*"competitivo" + 0.020*"cobros" + 0.019*"sol" + 0.019*"presion" + 0.018*"alto"
Topic #7: 0.181*"tiempo" + 0.072*"pago" + 0.057*"laborales" + 0.050*"esperaban" + 0.049*"trabajo" + 0.041*"incentivos" + 0.035*"tienda" + 0.032*"quincenal" + 0.031*"expectativas" + 0.029*"extenso"
Topic #8: 0.082*"falta" + 0.058*"parte" + 0.047*"seguimiento" + 0.042*"empresa" + 0.039*"prestaciones" + 0.039*"gerente" + 0.036*"mala" + 0.033*"trato" + 0.030*"jefe" + 0.029*"colaborador"
Topic #9: 0.103*"trabajo" + 0.055*"adaptan" + 0.046*"ser" + 0.036*"coppel" + 0.030*"tiempo" + 0.028*"ritmo" + 0.027*"puede" + 0.026*"colaboradores" + 0.023*"forma" + 0.020*"mismo"
column: P3_v
Topic #0: 0.152*"laboral" + 0.083*"ambiente" + 0.060*"mejores" + 0.044*"oportunidades" + 0.036*"ser" + 0.035*"mal" + 0.034*"buscan" + 0.029*"ingresos" + 0.027*"factor" + 0.027*"puede"
Topic #1: 0.099*"empresa" + 0.057*"salario" + 0.044*"trato" + 0.043*"tener" + 0.034*"tiempo" + 0.030*"mejor" + 0.028*"empleo" + 0.028*"faltantes" + 0.028*"pago" + 0.025*"gerentes"
Topic #2: 0.074*"actividades" + 0.045*"colaboradores" + 0.039*"realizar" + 0.033*"solo" + 0.022*"bien" + 0.020*"ser" + 0.020*"clientes" + 0.019*"muchas" + 0.018*"hacer" + 0.016*"hoy"
Topic #3: 0.127*"gusta" + 0.116*"trabajo" + 0.112*"responsabilidad" + 0.057*"adaptan" + 0.051*"quieren" + 0.036*"generaciones" + 0.035*"nuevas" + 0.035*"empresa" + 0.025*"gusto" + 0.021*"necesidades"
Topic #4: 0.240*"trabajo" + 0.090*"carga" + 0.058*"personal" + 0.048*"exigencia" + 0.023*"tiempo" + 0.022*"menos" + 0.022*"metas" + 0.022*"incentivos" + 0.021*"vez" + 0.018*"ritmo"
Topic #5: 0.380*"falta" + 0.089*"compromiso" + 0.056*"parte" + 0.056*"seguimiento" + 0.043*"mala" + 0.036*"gerente" + 0.032*"jefes" + 0.027*"jefe" + 0.024*"malos" + 0.021*"liderazgo"
Topic #6: 0.150*"sueldo" + 0.081*"tiempo" + 0.063*"laboral" + 0.060*"jornada" + 0.052*"prestaciones" + 0.040*"sueldos" + 0.036*"esperaban" + 0.028*"empresas" + 0.026*"mejores" + 0.024*"mejor"
Topic #7: 0.097*"metas" + 0.092*"trabajar" + 0.063*"bajo" + 0.047*"acostumbrados" + 0.045*"gusta" + 0.037*"sienten" + 0.036*"adaptan" + 0.029*"trabajo" + 0.027*"cobro" + 0.026*"forma"
Topic #8: 0.297*"horario" + 0.050*"trabajo" + 0.041*"expectativas" + 0.038*"laboral" + 0.036*"poca" + 0.034*"tienda" + 0.033*"tiempo" + 0.029*"coppel" + 0.026*"extenso" + 0.026*"laborales"
Topic #9: 0.266*"horarios" + 0.061*"personales" + 0.044*"responsabilidades" + 0.042*"puesto" + 0.039*"actividades" + 0.036*"funciones" + 0.031*"temas" + 0.027*"entrevista" + 0.023*"problemas" + 0.021*"cambio"
column: P4_n
Topic #0: 0.048*"tiendas" + 0.048*"competencia" + 0.042*"muchas" + 0.041*"ma" + 0.040*"trabajo" + 0.038*"prestaciones" + 0.032*"empresas" + 0.030*"horarios" + 0.027*"coppel" + 0.026*"mayor"
Topic #1: 0.141*"metas" + 0.061*"cultura" + 0.060*"laboral" + 0.035*"ambiente" + 0.030*"cumplimiento" + 0.027*"exigencia" + 0.027*"cumplir" + 0.025*"lograr" + 0.023*"condiciones" + 0.022*"nuevas"
Topic #2: 0.062*"ciudad" + 0.046*"centro" + 0.041*"diferentes" + 0.041*"faltante" + 0.030*"caso" + 0.029*"zona" + 0.026*"empleo" + 0.023*"solo" + 0.022*"colaboradores" + 0.019*"creo"
Topic #3: 0.240*"clientes" + 0.142*"afluencia" + 0.061*"poca" + 0.051*"tienda" + 0.042*"inseguridad" + 0.038*"tipo" + 0.034*"gente" + 0.024*"baja" + 0.018*"horario" + 0.017*"sucursal"
Topic #4: 0.125*"falta" + 0.092*"colaboradores" + 0.045*"sueldos" + 0.041*"compromiso" + 0.039*"mejores" + 0.039*"ninguna" + 0.038*"laboral" + 0.033*"cambio" + 0.032*"oferta" + 0.032*"alta"
Topic #5: 0.180*"tienda" + 0.105*"zona" + 0.073*"gente" + 0.033*"colaboradores" + 0.032*"grande" + 0.026*"cliente" + 0.022*"plaza" + 0.020*"encuentra" + 0.020*"formato" + 0.018*"mucha"
Topic #6: 0.052*"colaborador" + 0.048*"farderos" + 0.044*"zona" + 0.042*"colaboradores" + 0.040*"tienda" + 0.037*"tema" + 0.035*"planta" + 0.035*"alto" + 0.029*"seguridad" + 0.023*"robos"
Topic #7: 0.050*"cada" + 0.043*"ser" + 0.041*"centros" + 0.038*"centro" + 0.037*"colaboradores" + 0.037*"persona" + 0.032*"trabajar" + 0.031*"retador" + 0.028*"reto" + 0.026*"considero"
Topic #8: 0.217*"personal" + 0.069*"falta" + 0.027*"empresa" + 0.026*"cambios" + 0.025*"poder" + 0.024*"toda" + 0.024*"parte" + 0.024*"cubrir" + 0.022*"procesos" + 0.020*"centro"
Topic #9: 0.160*"trabajo" + 0.042*"entorno" + 0.039*"equipo" + 0.036*"carga" + 0.034*"localidad" + 0.033*"competencia" + 0.028*"condiciones" + 0.028*"actividades" + 0.028*"sueldo" + 0.026*"hacer"
column: P4_v
Topic #0: 0.074*"competencia" + 0.048*"horarios" + 0.046*"trabajo" + 0.045*"sueldo" + 0.044*"empresas" + 0.041*"tiendas" + 0.037*"prestaciones" + 0.033*"mejores" + 0.032*"sueldos" + 0.032*"coppel"
Topic #1: 0.080*"cada" + 0.072*"condiciones" + 0.051*"entorno" + 0.049*"inseguridad" + 0.037*"ciudad" + 0.034*"centro" + 0.034*"cambio" + 0.023*"internas" + 0.022*"colaboradores" + 0.021*"trabajo"
Topic #2: 0.153*"clientes" + 0.130*"afluencia" + 0.068*"poca" + 0.045*"centros" + 0.038*"carga" + 0.032*"gente" + 0.031*"trabajo" + 0.031*"ninguna" + 0.029*"puede" + 0.022*"ser"
Topic #3: 0.087*"clientes" + 0.068*"tienda" + 0.054*"tipo" + 0.040*"personas" + 0.034*"lograr" + 0.033*"sucursal" + 0.031*"cliente" + 0.028*"afluencia" + 0.027*"baja" + 0.027*"grande"
Topic #4: 0.153*"metas" + 0.067*"cultura" + 0.034*"venta" + 0.033*"cumplimiento" + 0.028*"cumplir" + 0.028*"manera" + 0.026*"colaboradores" + 0.025*"hace" + 0.024*"seguimiento" + 0.023*"tiempo"
Topic #5: 0.140*"personal" + 0.045*"farderos" + 0.039*"zona" + 0.033*"faltante" + 0.027*"responsabilidad" + 0.026*"menos" + 0.026*"centro" + 0.025*"muebles" + 0.024*"dentro" + 0.024*"ropa"
Topic #6: 0.183*"falta" + 0.154*"tienda" + 0.073*"personal" + 0.045*"transporte" + 0.027*"colaboradores" + 0.026*"trabajo" + 0.023*"seguridad" + 0.022*"trabajar" + 0.020*"robos" + 0.019*"zona"
Topic #7: 0.091*"zona" + 0.085*"gente" + 0.052*"mucha" + 0.050*"trabajo" + 0.049*"mas" + 0.030*"oferta" + 0.028*"localidad" + 0.024*"hace" + 0.020*"productos" + 0.019*"laboral"
Topic #8: 0.077*"laboral" + 0.044*"personal" + 0.037*"planta" + 0.035*"ambiente" + 0.034*"clientes" + 0.032*"cantidad" + 0.029*"trabajo" + 0.028*"demanda" + 0.028*"horario" + 0.026*"alta"
Topic #9: 0.112*"colaboradores" + 0.041*"centro" + 0.034*"tener" + 0.029*"solo" + 0.024*"colaborador" + 0.023*"empresa" + 0.023*"gerente" + 0.020*"compromiso" + 0.019*"cambios" + 0.017*"actividades"
column: P5_n
Topic #0: 0.067*"mayor" + 0.063*"planta" + 0.053*"salario" + 0.051*"incentivo" + 0.035*"actividades" + 0.034*"colaborador" + 0.031*"constante" + 0.027*"mejor" + 0.027*"colaboradores" + 0.025*"ma"
Topic #1: 0.052*"colaboradores" + 0.038*"trabajo" + 0.036*"tener" + 0.032*"tiempo" + 0.030*"clientes" + 0.027*"tienda" + 0.027*"poder" + 0.025*"personal" + 0.024*"sistema" + 0.021*"carga"
Topic #2: 0.075*"personal" + 0.032*"herramientas" + 0.031*"horario" + 0.031*"considero" + 0.030*"solo" + 0.029*"empresa" + 0.027*"decisiones" + 0.025*"ser" + 0.022*"toda" + 0.020*"colaboradores"
Topic #3: 0.038*"persona" + 0.038*"empresa" + 0.036*"trabajo" + 0.034*"equipo" + 0.034*"colaboradores" + 0.027*"trabajar" + 0.025*"apoyo" + 0.024*"cada" + 0.024*"manera" + 0.023*"colaborador"
Topic #4: 0.115*"laboral" + 0.066*"colaborador" + 0.051*"gerentes" + 0.049*"gerente" + 0.043*"ambiente" + 0.039*"buen" + 0.038*"parte" + 0.029*"mejor" + 0.028*"trato" + 0.026*"colaboradores"
Topic #5: 0.184*"sueldo" + 0.080*"apoyo" + 0.073*"transporte" + 0.055*"mejorar" + 0.047*"incremento" + 0.046*"mejor" + 0.033*"puesto" + 0.027*"ahorro" + 0.025*"horario" + 0.022*"aumento"
Topic #6: 0.189*"horarios" + 0.094*"sueldos" + 0.062*"trabajo" + 0.059*"turnos" + 0.059*"mejores" + 0.048*"ma" + 0.037*"procesos" + 0.034*"mejorar" + 0.028*"flexibles" + 0.026*"cargas"
Topic #7: 0.206*"seguimiento" + 0.077*"desarrollo" + 0.072*"platicas" + 0.050*"entrenamiento" + 0.044*"plan" + 0.037*"platica" + 0.037*"dec" + 0.035*"coppel" + 0.022*"beneficios" + 0.020*"proceso"
Topic #8: 0.236*"incentivos" + 0.055*"metas" + 0.030*"mejorar" + 0.029*"mejores" + 0.027*"alcanzables" + 0.025*"esquema" + 0.023*"mejora" + 0.022*"faltante" + 0.022*"capacitaciones" + 0.020*"ganar"
Topic #9: 0.322*"prestaciones" + 0.054*"pago" + 0.039*"cursos" + 0.037*"beneficios" + 0.030*"empresa" + 0.028*"semanal" + 0.027*"mayores" + 0.025*"coppel" + 0.023*"crecimiento" + 0.016*"conocer"
column: P5_v
Topic #0: 0.254*"incentivos" + 0.076*"metas" + 0.054*"mejores" + 0.053*"incentivo" + 0.047*"salario" + 0.032*"mejor" + 0.029*"alcanzables" + 0.027*"esquema" + 0.025*"salarios" + 0.021*"ser"
Topic #1: 0.155*"mejorar" + 0.097*"horario" + 0.089*"sueldos" + 0.059*"pago" + 0.052*"sueldo" + 0.037*"semanal" + 0.037*"herramientas" + 0.035*"mejores" + 0.028*"semana" + 0.026*"cambio"
Topic #2: 0.274*"prestaciones" + 0.105*"laboral" + 0.044*"beneficios" + 0.041*"coppel" + 0.039*"ambiente" + 0.029*"todas" + 0.028*"buen" + 0.023*"descansos" + 0.022*"mayores" + 0.020*"vacaciones"
Topic #3: 0.198*"trabajo" + 0.043*"planta" + 0.038*"carga" + 0.036*"actividades" + 0.035*"dec" + 0.031*"personal" + 0.028*"aumento" + 0.026*"equipo" + 0.026*"mas" + 0.023*"cargas"
Topic #4: 0.164*"seguimiento" + 0.061*"desarrollo" + 0.060*"cursos" + 0.057*"platicas" + 0.043*"plan" + 0.042*"procesos" + 0.041*"entrenamiento" + 0.032*"decisiones" + 0.029*"platica" + 0.024*"colaboradores"
Topic #5: 0.078*"personal" + 0.065*"apoyo" + 0.061*"tienda" + 0.060*"colaboradores" + 0.045*"tener" + 0.040*"mayor" + 0.035*"transporte" + 0.024*"planta" + 0.022*"seguridad" + 0.019*"tiendas"
Topic #6: 0.078*"colaborador" + 0.045*"cada" + 0.032*"colaboradores" + 0.029*"solo" + 0.027*"puesto" + 0.024*"gerente" + 0.020*"apoyo" + 0.020*"empresa" + 0.020*"constante" + 0.018*"parte"
Topic #7: 0.089*"empresa" + 0.064*"bien" + 0.035*"personas" + 0.035*"considero" + 0.031*"muchas" + 0.029*"faltante" + 0.028*"veces" + 0.026*"descanso" + 0.024*"muebles" + 0.022*"gente"
Topic #8: 0.210*"horarios" + 0.122*"sueldo" + 0.057*"turnos" + 0.051*"incremento" + 0.040*"mejora" + 0.032*"laborales" + 0.030*"do" + 0.029*"flexibles" + 0.027*"jornadas" + 0.026*"mejor"
Topic #9: 0.037*"manera" + 0.029*"tiempo" + 0.028*"mejor" + 0.026*"gerentes" + 0.025*"colaboradores" + 0.023*"colaborador" + 0.021*"ser" + 0.020*"necesidades" + 0.020*"buena" + 0.019*"realmente"
column: P6_n
Topic #0: 0.065*"gerentes" + 0.053*"laboral" + 0.050*"colaboradores" + 0.040*"ambiente" + 0.033*"puesto" + 0.026*"gracias" + 0.023*"cada" + 0.021*"zona" + 0.019*"parte" + 0.018*"apoyo"
Topic #1: 0.081*"sueldo" + 0.066*"colaboradores" + 0.053*"empresa" + 0.043*"personal" + 0.025*"hace" + 0.025*"sienten" + 0.023*"jefes" + 0.022*"menos" + 0.022*"tema" + 0.019*"mejorar"
Topic #2: 0.045*"colaborador" + 0.035*"empresa" + 0.033*"cuenta" + 0.028*"colaboradores" + 0.024*"tomar" + 0.022*"parte" + 0.022*"salida" + 0.021*"mayor" + 0.019*"seguimiento" + 0.018*"vida"
Topic #3: 0.049*"metas" + 0.044*"falta" + 0.042*"personal" + 0.027*"colaboradores" + 0.027*"ma" + 0.027*"trabajo" + 0.025*"clientes" + 0.025*"tienda" + 0.022*"solo" + 0.020*"centros"

In [ ]:
# 1. ¿Qué crees que ha hecho que algunas personas lleven tanto tiempo en la empresa?,
# 2. ¿A qué atribuyes que algunos Colaboradores renuncien teniendo poco tiempo laborando en la empresa?,
# 3. ¿A qué atribuyes que algunos Colaboradores renuncien teniendo mucho tiempo laborando en la empresa?,
# 4. ¿Qué condiciones internas y/o del entorno (de la localidad) hacen que liderar este centro sea más retador que otros?,
# "5. ¿Qué apoyos, decisiones o herramientas (internas o externas) podrían ayudar a mejorar la permanencia?",
# 6. ¿Hay algo que no te hayamos preguntado y que consideres importante agregar para poder comprender por qué los Colaboradores toman la decisión de salir de la empresa?